tasks/urls.py
from django.urls import path

from tasks.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskChangeIsDoneView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
)

urlpatterns = [
    # Tasks
    path("", TaskListView.as_view(), name="task-list"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/update/isdone/", TaskChangeIsDoneView.as_view(), name="task-update-isdone"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),

    # Tags
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tag/create/", TagCreateView.as_view(), name="tag-create"),
    path("tag/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tag/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "tasks"

to_di_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tasks.urls", namespace="tasks"))
]

tasks/models.py
from django.db import models


class Task(models.Model):
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now=True)
    deadline = models.DateTimeField(null=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField("Tag", related_name="tasks")

    class Meta:
        ordering = ("is_done", "created_at",)
        verbose_name = "task"
        verbose_name_plural = "tasks"

    def __str__(self):
        return f"{self.content} ({self.is_done})"


class Tag(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = "tag"
        verbose_name_plural = "tags"

    def __str__(self):
        return self.name

tasks/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic, View

from tasks.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    template_name = "tasks/task_list.html"
    context_object_name = "task_list"


class TaskCreateView(generic.CreateView):
    model = Task
    fields = ("content", "deadline", "tags",)
    template_name = "tasks/task_form.html"
    success_url = reverse_lazy("tasks:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    template_name = "tasks/task_form.html"
    success_url = reverse_lazy("tasks:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("tasks:task-list")
    template_name = "tasks/task_confirm_delete.html"


class TaskChangeIsDoneView(View):
    def post(self, request, pk, *args, **kwargs):
        task = get_object_or_404(Task, pk=pk)
        task.is_done = not task.is_done
        task.save()
        return redirect("tasks:task-list")


class TagListView(generic.ListView):
    model = Tag
    template_name = "tasks/tag_list.html"
    context_object_name = "tag_list"


class TagCreateView(generic.CreateView):
    model = Tag
    fields = ("name",)
    template_name = "tasks/tag_form.html"
    success_url = reverse_lazy("tasks:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = ("name",)
    template_name = "tasks/tag_form.html"
    success_url = reverse_lazy("tasks:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("tasks:tag-list")
    template_name = "tasks/tag_confirm_delete.html"

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>Task Manager</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">
</head>
<body>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2 mb-3 p-2">
      {% block navigration %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    </div>
    <div class="col-sm-9 mb-3 p-2">
      {% block content %}{% endblock %}
    </div>
  </div>
</div>

</body>
</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'tasks:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'tasks:tag-list' %}">Tags</a></li>
</ul>

templates/tasks/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Tag</h1>

  <p>Are you sure you want to delete the tag: {{ tag.name }}?</p>
  <form method="post" action="">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
  </form>
{% endblock %}

templates/tasks/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>
    {{ object|yesno:"Update,Create" }}
    Tag
  </h1>
  <form method="post" action="">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="Submit" value="{{ object|yesno:"Update,Create" }}">
  </form>
{% endblock %}

templates/tasks/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1 class="d-flex align-items-center">
    Tag list
    <a href="{% url 'tasks:tag-create' %}" class="btn btn-primary link-to-page ml-auto">
      Add tag
    </a>
  </h1>
  {% if tag_list %}
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for tag in tag_list %}
          <tr>
            <td>{{ tag.name }}</td>
            <td>
              <a href="{% url 'tasks:tag-update' tag.id %}" class="btn btn-sm btn-secondary">Update</a>
            </td>
            <td>
              <a href="{% url 'tasks:tag-delete' tag.id %}" class="btn btn-sm btn-danger">Delete</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>There are no tags yet</p>
  {% endif %}
{% endblock %}

templates/tasks/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Task</h1>

  <p>Are you sure you want to delete the task: {{ task.content }}?</p>
  <form method="post" action="">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
  </form>
{% endblock %}

templates/tasks/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>
    {{ object|yesno:"Update,Create" }}
    Task
  </h1>
  <form method="post" action="">
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="Submit" value="{{ object|yesno:"Update,Create" }}">
  </form>
{% endblock %}

templates/tasks/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1 class="d-flex align-items-center">
    TODO list
    <a href="{% url 'tasks:task-create' %}" class="btn btn-primary link-to-page ml-auto">
      Add task
    </a>
  </h1>
  {% if task_list %}
    <ul class="list-group">
      {% for task in task_list %}
        <li class="list-group-item">
          <h3 class="d-flex align-items-center">
            <strong>{{ task.content }}</strong>
            {% if task.is_done %}
              <p class="text-success mb-0 ml-2">Done</p>
              <form method="post" action="{% url 'tasks:task-update-isdone' task.id %}" class="ml-auto">
                {% csrf_token %}
                <button type="submit" class="btn btn-secondary">Undo</button>
              </form>
            {% else %}
              <p class="text-danger mb-0 ml-2">Not done</p>
              <form method="post" action="{% url 'tasks:task-update-isdone' task.id %}" class="ml-auto">
                {% csrf_token %}
                <button type="submit" class="btn btn-success">Complete</button>
              </form>
            {% endif %}
          </h3>
          <p>Created: {{ task.created_at }}</p>
          <p>Deadline: {{ task.deadline }}</p>
          <h4 class="text-secondary">
            Tags: {% for tag in task.tags.all %}{{ tag.name }} {% endfor %}
            <a class="link-primary" href="{% url 'tasks:task-update' task.id %}">Update</a>
            <a class="link-primary" href="{% url 'tasks:task-delete' task.id %}">Delete</a>
          </h4>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no tasks yet</p>
  {% endif %}
{% endblock %}